In [12]:
import pandas as pd
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [46]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [52]:
from evaluation.evaluate_script import graph_eval_readable_ranking_main, graph_eval_readable_ranking_comparable_main

In [35]:
import pickle
from evaluation.evaluate_script import graph_eval_ranking_first
import os
import json

file = "/home/kardosp/continuethelist/outputs/graphwalk_v2_output_sample4.pickle"

with open(file, "rb") as f:
    algo_results = pickle.load(f)

In [ ]:
res_matrix = graph_eval_readable_ranking_main(algo_results, "/home/kardosp/continuethelist/stats/visualized_outputs/graphwalk_v2_ranking.xlsx")

In [ ]:
graph_eval_readable_ranking_comparable_main(algo_results, "/home/kardosp/continuethelist/stats/visualized_outputs/graphwalk_v2_comparable")

 63%|█████████████████████████▉               | 158/250 [06:07<03:45,  2.45s/it]

In [134]:
res_matrix_compare

[[[['?x',
    '<http://dbpedia.org/property/operator>',
    '<http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide>'],
   ['?x', '<http://dbpedia.org/property/address>', '?uri']],
  '181',
  'http://dbpedia.org/resource/California',
  'http://dbpedia.org/resource/San_Francisco',
  '2',
  'Calle San Fernando, 2',
  '1',
  'http://dbpedia.org/resource/Chennai',
  'http://dbpedia.org/resource/Tamil_Nadu',
  'Krakowskie Przedmiescie 42/44',
  '1900',
  'http://dbpedia.org/resource/Seattle',
  '811',
  '333',
  '210',
  'http://dbpedia.org/resource/Atlanta',
  '10600',
  'http://dbpedia.org/resource/Westminster,_Colorado',
  'Main Gulshan Avenue, Plot-01, Road 45, Gulshan-2, Dhaka 1212, Bangladesh',
  '211',
  'http://dbpedia.org/resource/San_Jose,_California'],
 [[['?x',
    '<http://dbpedia.org/property/operator>',
    '<http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide>'],
   ['?x', '<http://dbpedia.org/property/address>', '?uri']],
  '181',
  'http://dbpedia.org/resource/California',
  'http://dbpedia.org/resource/San_Francisco',
  '2',
  'Calle San Fernando, 2',
  '1',
  'http://dbpedia.org/resource/Chennai',
  'http://dbpedia.org/resource/Tamil_Nadu',
  'Krakowskie Przedmiescie 42/44',
  '1900',
  'http://dbpedia.org/resource/Seattle',
  '811',
  '333',
  '210',
  'http://dbpedia.org/resource/Atlanta',
  '10600',
  'http://dbpedia.org/resource/Westminster,_Colorado',
  'Main Gulshan Avenue, Plot-01, Road 45, Gulshan-2, Dhaka 1212, Bangladesh',
  '211',
  'http://dbpedia.org/resource/San_Jose,_California'],
 [[['?dy', 'http://dbpedia.org/property/address', '?uri'],
   ['?dy',
    'http://dbpedia.org/ontology/tenant',
    'http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide']],
  '181',
  'http://dbpedia.org/resource/California',
  'http://dbpedia.org/resource/San_Francisco',
  '2',
  'Calle San Fernando, 2',
  '1',
  'http://dbpedia.org/resource/Chennai',
  'http://dbpedia.org/resource/Tamil_Nadu',
  'Krakowskie Przedmiescie 42/44',
  '1900',
  'http://dbpedia.org/resource/Seattle',
  '811',
  '333',
  '10600',
  'http://dbpedia.org/resource/Westminster,_Colorado',
  'Main Gulshan Avenue, Plot-01, Road 45, Gulshan-2, Dhaka 1212, Bangladesh',
  '211',
  'http://dbpedia.org/resource/San_Jose,_California'],
 [],
 [],
 [],
 [[['?dr', 'http://dbpedia.org/property/address', '?uri'],
   ['?dr',
    'http://dbpedia.org/property/operator',
    'http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide']],
  '181',
  'http://dbpedia.org/resource/California',
  'http://dbpedia.org/resource/San_Francisco',
  '2',
  'Calle San Fernando, 2',
  '1',
  'http://dbpedia.org/resource/Chennai',
  'http://dbpedia.org/resource/Tamil_Nadu',
  'Krakowskie Przedmiescie 42/44',
  '1900',
  'http://dbpedia.org/resource/Seattle',
  '811',
  '333',
  '210',
  'http://dbpedia.org/resource/Atlanta',
  '10600',
  'http://dbpedia.org/resource/Westminster,_Colorado',
  'Main Gulshan Avenue, Plot-01, Road 45, Gulshan-2, Dhaka 1212, Bangladesh',
  '211',
  'http://dbpedia.org/resource/San_Jose,_California']]

In [135]:
import numpy as np
import pandas as pd
max_column_length = len(max(res_matrix_compare,key = lambda x: len(x)))

In [136]:
for i in range(len(res_matrix_compare)):
    while len(res_matrix_compare[i]) != max_column_length:
        res_matrix_compare[i].append("")

In [137]:
pdf = pd.DataFrame(res_matrix_compare).transpose()
pdf.columns =  ["gold_nodes"] + [f"pred_{i}" for i in range(5)] + ["match_nodes"]

In [138]:
pdf

,gold_nodes,pred_0,pred_1,pred_2,pred_3,pred_4,match_nodes
0,"[[?x, <http://dbpedia.org/property/operator>, ...","[[?x, <http://dbpedia.org/property/operator>, ...","[[?dy, http://dbpedia.org/property/address, ?u...",,,,"[[?dr, http://dbpedia.org/property/address, ?u..."
1,181,181,181,,,,181
2,http://dbpedia.org/resource/California,http://dbpedia.org/resource/California,http://dbpedia.org/resource/California,,,,http://dbpedia.org/resource/California
3,http://dbpedia.org/resource/San_Francisco,http://dbpedia.org/resource/San_Francisco,http://dbpedia.org/resource/San_Francisco,,,,http://dbpedia.org/resource/San_Francisco
4,2,2,2,,,,2
5,"Calle San Fernando, 2","Calle San Fernando, 2","Calle San Fernando, 2",,,,"Calle San Fernando, 2"
6,1,1,1,,,,1
7,http://dbpedia.org/resource/Chennai,http://dbpedia.org/resource/Chennai,http://dbpedia.org/resource/Chennai,,,,http://dbpedia.org/resource/Chennai
8,http://dbpedia.org/resource/Tamil_Nadu,http://dbpedia.org/resource/Tamil_Nadu,http://dbpedia.org/resource/Tamil_Nadu,,,,http://dbpedia.org/resource/Tamil_Nadu
9,Krakowskie Przedmiescie 42/44,Krakowskie Przedmiescie 42/44,Krakowskie Przedmiescie 42/44,,,,Krakowskie Przedmiescie 42/44
10,1900,1900,1900,,,,1900
11,http://dbpedia.org/resource/Seattle,http://dbpedia.org/resource/Seattle,http://dbpedia.org/resource/Seattle,,,,http://dbpedia.org/resource/Seattle
12,811,811,811,,,,811
13,333,333,333,,,,333
14,210,210,10600,,,,210
15,http://dbpedia.org/resource/Atlanta,http://dbpedia.org/resource/Atlanta,"http://dbpedia.org/resource/Westminster,_Colorado",,,,http://dbpedia.org/resource/Atlanta
16,10600,10600,"Main Gulshan Avenue, Plot-01, Road 45, Gulshan...",,,,10600
17,"http://dbpedia.org/resource/Westminster,_Colorado","http://dbpedia.org/resource/Westminster,_Colorado",211,,,,"http://dbpedia.org/resource/Westminster,_Colorado"
18,"Main Gulshan Avenue, Plot-01, Road 45, Gulshan...","Main Gulshan Avenue, Plot-01, Road 45, Gulshan...","http://dbpedia.org/resource/San_Jose,_California",,,,"Main Gulshan Avenue, Plot-01, Road 45, Gulshan..."
19,211,211,,,,,211
20,"http://dbpedia.org/resource/San_Jose,_California","http://dbpedia.org/resource/San_Jose,_California",,,,,"http://dbpedia.org/resource/San_Jose,_California"

In [141]:
gold_nodes = pdf["gold_nodes"].tolist()[1:]
pdf.style.apply(lambda x: ["background: green" if v in gold_nodes else "" for v in x], axis = 1)

In [62]:
import pandas as pd

In [17]:
pd.DataFrame(res_matrix)

,0,1,2,3,4,5,6,7,8,9,10,11
0,"[[[?x, <http://dbpedia.org/property/operator>,...","[[[?dy, http://dbpedia.org/property/address, ?...",,,,,,,,,,"[[[?dr, http://dbpedia.org/property/address, ?..."
1,"[[[?x, <http://dbpedia.org/property/publisher>...","[[[?al, http://dbpedia.org/ontology/nonFiction...",,,,,,,,,,"[[[?at, http://dbpedia.org/property/subject, ?..."
2,"[[[<http://dbpedia.org/resource/Arkansas>, <ht...",,,,,,,,,,,"[[[?ar, http://dbpedia.org/property/region, ?u..."
3,"[[[?x, <http://dbpedia.org/property/currentMem...",,,,,,,,,,,"[[[http://dbpedia.org/resource/Skull_Gang, htt..."
4,"[[[?x, <http://dbpedia.org/property/magazine>,...","[[[?as, http://dbpedia.org/ontology/author, ?u...","[[[?au, http://dbpedia.org/ontology/author, ?u...",,,,,,,,,"[[[?ai, http://dbpedia.org/property/author, ?u..."
5,"[[[?uri, <http://dbpedia.org/ontology/order>, ...",,,,,,,,,,,
6,"[[[?uri, <http://dbpedia.org/ontology/formerTe...",,,,,,,,,,,
7,"[[[?x, <http://dbpedia.org/property/headquarte...",,,,,,,,,,,
8,"[[[?uri, <http://dbpedia.org/ontology/origin>,...",,,,,,,,,,,
9,"[[[?uri, <http://dbpedia.org/property/distribu...",,,,,,,,,,,

In [18]:
pdf = pd.DataFrame(res_matrix)

pdf.columns = ["gold"] + [f"pred_{i}" for i in range(10)] + ["match"]

In [19]:
pdf

,gold,pred_0,pred_1,pred_2,pred_3,pred_4,pred_5,pred_6,pred_7,pred_8,pred_9,match
0,"[[[?x, <http://dbpedia.org/property/operator>,...","[[[?dy, http://dbpedia.org/property/address, ?...",,,,,,,,,,"[[[?dr, http://dbpedia.org/property/address, ?..."
1,"[[[?x, <http://dbpedia.org/property/publisher>...","[[[?al, http://dbpedia.org/ontology/nonFiction...",,,,,,,,,,"[[[?at, http://dbpedia.org/property/subject, ?..."
2,"[[[<http://dbpedia.org/resource/Arkansas>, <ht...",,,,,,,,,,,"[[[?ar, http://dbpedia.org/property/region, ?u..."
3,"[[[?x, <http://dbpedia.org/property/currentMem...",,,,,,,,,,,"[[[http://dbpedia.org/resource/Skull_Gang, htt..."
4,"[[[?x, <http://dbpedia.org/property/magazine>,...","[[[?as, http://dbpedia.org/ontology/author, ?u...","[[[?au, http://dbpedia.org/ontology/author, ?u...",,,,,,,,,"[[[?ai, http://dbpedia.org/property/author, ?u..."
5,"[[[?uri, <http://dbpedia.org/ontology/order>, ...",,,,,,,,,,,
6,"[[[?uri, <http://dbpedia.org/ontology/formerTe...",,,,,,,,,,,
7,"[[[?x, <http://dbpedia.org/property/headquarte...",,,,,,,,,,,
8,"[[[?uri, <http://dbpedia.org/ontology/origin>,...",,,,,,,,,,,
9,"[[[?uri, <http://dbpedia.org/property/distribu...",,,,,,,,,,,

In [27]:
x = pdf["gold"].tolist()[0]

In [29]:
for item in x[0]:
    print(item)

['?x', '<http://dbpedia.org/property/operator>', '<http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide>']
['?x', '<http://dbpedia.org/property/address>', '?uri']

In [32]:
x[0][0]

['?x',
 '<http://dbpedia.org/property/operator>',
 '<http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide>']

In [66]:
len(res_matrix[0][0])

2

In [67]:
res_matrix[2]

[[[['resource/Arkansas', 'ontology/language', '?x'],
   ['?x', 'property/region', '?uri'],
   ['?x',
    '<http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
    'ontology/EthnicGroup']],
  11],
 [[['?ar', 'http://dbpedia.org/property/region', '?uri'],
   ['?ar',
    'http://purl.org/dc/terms/subject',
    'http://dbpedia.org/resource/Category:English-American_history']]]]

In [69]:
res_matrix[0]

[[[['?x',
    'property/operator',
    'resource/Starwood_Hotels_and_Resorts_Worldwide'],
   ['?x', 'property/address', '?uri']],
  20],
 [[['?dy', 'http://dbpedia.org/property/address', '?uri'],
   ['?dy',
    'http://dbpedia.org/ontology/tenant',
    'http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide']],
  22],
 [[['?dr', 'http://dbpedia.org/property/address', '?uri'],
   ['?dr',
    'http://dbpedia.org/property/operator',
    'http://dbpedia.org/resource/Starwood_Hotels_and_Resorts_Worldwide']]]]